services:
  mysql-test:
    image: mysql:8.0
    container_name: clails_test_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    tmpfs:
      - /var/lib/mysql
#    volumes:
#      - ./volumes/mysql:/var/lib/mysql
  postgresql-test:
    image: postgres:16.3
    container_name: clails_test_postgresql
    environment:
      POSTGRES_USER: clails
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    tmpfs:
      - /var/lib/postgresql/data
      - /var/log
#    volumes:
#      - ./volumes/postgresql/data:/var/lib/postgresql/data
#      - ./volumes/postgresql/log:/var/log
