services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_USER=clails-user
      - MYSQL_PASSWORD=clails-password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - clails_dev_nw
networks:
  clails_dev_nw:
    external: true

