services:
  postgresql:
    image: postgres:16.3
    environment:
      POSTGRES_USER: clails
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - clails_dev_nw
networks:
  clails_dev_nw:
    external: true
